### ISSUE TITLE
IndexOutOfBounds

### ISSUE THREAD

**Issue by rishabh3** [dude-pa/dude#10]
What are the steps to reproduce this issue?
-------------------------------------------
1. Run the command "dude diary ct".
2. When it asks for the task number enter any number which is greater than the task number in the given list. 

What happens?
-------------
The program crashes and generate a very unpleasant error message stating index out of range. 

What were you expecting to happen?
----------------------------------
It should have presented the error in nice way like re-ask for the same task number by displaying messages like "You had input a wrong task number before" or something like that!

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu Gnome 16.04.02

Feature description:
-------------------
NA

Any ideas on how to implement it?
---------------------------------
You can make a conditional check for the input to be less than the maximum task number. Loop to prompt for the input by displaying proper error message!

Any other comments?
-------------------
NA
Any feedback on the project?
-------------------
Very nice and interesting project

**Comment by manparvesh** [comment]
@rishabh3 your repo is not synced with the main repo, you can do so by taking a look [here](https://help.github.com/articles/syncing-a-fork/).
The changes made in your repository are not added into a pull request. You need to create a new pull request every time you make some changes.
Since this issue is not resolved in the main repo, I am reopening it.
Please read about using Git and Github online

**Comment by rishabh3** [comment]
Oh K I will look through it
